###get
GET http://localhost:3000/players/

###get player Id
GET http://localhost:3000/players/3/

###put
PUT http://localhost:3000/players/2/
Content-Type: application/json

{
  "playerName": "Raju"
}

### get match Id
GET http://localhost:3000/matches/5/

### get all match details
GET http://localhost:3000/players/1/matches

### get specific players
GET http://localhost:3000/matches/1/players

### get tortalm scores
GET http://localhost:3000/players/2/playerScores
